### ISSUE TITLE
install-pks pipeline has hardcoded vsphere

### ISSUE THREAD

**Issue by JasonMorgan** [pivotalservices/concourse-pipeline-samples#11]
the upload-tile task has vsphere hardcoded as the IAAS:

```yaml
task: upload-tile
    file: pcf-pipelines/tasks/upload-product-and-stemcell/task.yml
    params:
      IAAS: vsphere
```

It would be good if it would switch to "google" when you set GCP as the target.

```yaml
task: upload-tile
    file: pcf-pipelines/tasks/upload-product-and-stemcell/task.yml
    params:
      IAAS: google
```
